data_path: /home/mogab/code/dev/neuraloperator/data/ns_V1e-4_N10_000_T30.pth
n_train: 2000
n_test: 500
train_batch_size: 50
test_batch_size: 20
learning_rate: 0.001
epochs: 500
# Should be: iterations = epochs * (n_train // train_batch_size)
iterations: 20_000
modes: 12
width: 20
subsampling_rate: 1
s: 64
history_length: 10
# T=40 for V1e-3; T=20 for V1e-4; T=10 for V1e-5;
future_duration: 20
step: 1
